name: Docker Build Push

inputs:
  image_name:
    required: true

runs:
  using: composite

  steps:
    - shell: bash
      run: echo "Building Docker Image"

    - shell: bash
      run: echo "Tagging Docker Image"

    - shell: bash
      run: echo "Pushing Docker Image"
