jobs:
  docker:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build Tag Push
        uses: ./.github/actions/docker-build-push
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          image_name: employee-management
          image_tag: latest
