  name: Base node

  on:
   workflow_dispatch:

  jobs:
    node:
      runs-on: [self-hosted,fsd-bharath]
    
    steps:
     name: Clone code
     uses: action/checkout@v7

     name: Node Install
     uses: action/checkout@v6
     with:
       node-version: 24

     name: Install Dependencies
     run: npm install

   name: Run Application
   run:
       node app.js
       sleep 5
       curl https://localhost:8080
       curl https://localhost:8080/health
       pkill -f "node app.js"
       
     
      
    
      
    

