name: Pull Request SonarQube

on:
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test workflow
        run: echo "SonarQube workflow is working"
